version: "3.9"
services:

  rabbitmq:
    image: rabbitmq:3
    ports:
      - "0.0.0.0:5672:5672"
    networks:
      - app-network

  server:
    build: ./server
    ports:
      - "0.0.0.0:8080:8080"
    depends_on:
      - rabbitmq
    environment:
      - AMQP_HOST=rabbitmq
    networks:
      - app-network

  client:
    build: ./client
    ports:
      - "0.0.0.0:3000:3000"
    depends_on:
      - server
    networks:
      - app-network

  worker:
    build: ./worker
    ports:
      - "0.0.0.0:8000:8000"
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge